- .npmignore
> chore: added config files to npmignore

- .github/renovate.json
> chore: group renovate dependencies by manager

- .github/renovate.json
> fix: pin node version to 18.x

- .github/workflows/stale-issues.yaml
> chore: add stale-issues workflow

- .github/workflows/build.yml
- .github/workflows/release.yml
- package.json
- yarn.lock
> fix: update dependencies and add missing docker build-args

- .release-it.cjs
- README.md
- package.json
- yarn.lock
> fix(ci): updated readme during release

- .github/workflows/release.yml
- package.json
> fix: use newly released version in docker build

- .github/workflows/release.yml
- package.json
- yarn.lock
> fix: determine docker release version

- README.md
- src/home-assistant/home-assistant-matter-adapter.ts
> feat(input_boolean): add support for input_boolean (#96)

- .github/workflows/pull-request-build.yml
- .github/workflows/release.yml
- README.md
- src/home-assistant/home-assistant-matter-adapter.ts
Fixes t0bst4r/matterbridge-home-assistant-addon#65
> fix(climate): disable climate support since it is not working yet

- .github/workflows/pull-request-build.yml
- docker/Dockerfile
- docker/docker-entrypoint.sh
- package.json
> fix: make matterbridge a devDependency (#97)

- .github/workflows/release.yml
> fix: release workflow broke with chore commits

- src/devices/aspects/door-lock-aspect.ts
- src/devices/home-assistant-device.ts
- src/devices/lock-device.ts
- src/home-assistant/home-assistant-matter-adapter.ts
> feat(lock): add lock support (#86)

- .github/workflows/release.yml
> Describe the changes you made.
> Related issues or pull requests
> fix(ci): pass latest-version to the addon repository

- .github/ISSUE_TEMPLATE/domain-request.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
> Describe the changes you made.
> Related issues or pull requests
> chore: update issue templates

- README.md
- src/devices/aspects/boolean-state-aspect.ts
- src/devices/aspects/color-control-aspect.ts
- src/devices/aspects/level-control-aspect.ts
- src/devices/aspects/occupancy-sensing-aspect.ts
- src/devices/light-device.ts
- src/util/color-converter.ts
- src/util/xy-to-rgb.ts
- test/util/color-converter.test.ts
> feat(light): add support for xy color mode (#110)

- src/devices/aspects/level-control-aspect.ts
- t0bst4r/matterbridge-home-assistant-addon#84
> fix(light): exit update loop when level control is not supported

- src/devices/aspects/color-control-aspect.ts
- src/util/color-converter.ts
- test/util/color-converter.test.ts
> Describe the changes you made.
> Related issues or pull requests
> fix(light): limit hue to 254 (#142)

- src/devices/aspects/basic-information-aspect.ts
- src/devices/home-assistant-device.ts
> feat(all-domains): add support for reachability

- package-lock.json
- packages/matterbridge-home-assistant/package.json
- packages/matterbridge-home-assistant/src/index.ts
> Describe the changes you made.
> Related issues or pull requests
> feat: allow JSON5 syntax for matterbridge configs (#219)

- packages/home-assistant-matter-hub/src/aspects/window-covering-aspect.ts
> fix: invert covers and make them nullsafe (#234, #235)

- packages/home-assistant-matter-hub/src/home-assistant-client/home-assistant-client.ts
> fix: only include included entities into warnings (#238)

- package-lock.json
- packages/home-assistant-matter-hub/package.json
- packages/home-assistant-matter-hub/src/aspects/window-covering-aspect.ts
- packages/home-assistant-matter-hub/src/devices/cover-device.ts
- packages/home-assistant-matter-hub/src/devices/index.ts
- packages/home-assistant-matter-hub/src/matter/matter-connector.ts
- packages/matterbridge-home-assistant/README.md
> fix(cover): support configuration of single or all covers (#234)

- packages/home-assistant-matter-hub/src/aspects/color-control-aspect.ts
- packages/home-assistant-matter-hub/src/aspects/level-control-aspect.ts
- packages/home-assistant-matter-hub/src/aspects/utils/color-control-cluster.ts
- packages/home-assistant-matter-hub/src/aspects/utils/noop-fn.ts
- packages/home-assistant-matter-hub/src/devices/fan-device.ts
- packages/home-assistant-matter-hub/src/devices/index.ts
- packages/home-assistant-matter-hub/src/home-assistant-client/home-assistant-client.ts
- packages/home-assistant-matter-hub/src/matter/matter-connector.ts
- packages/matterbridge-home-assistant/README.md
> feat(fan): add support for fans as dimmable switch (#70)

- .github/workflows/release.yml
- package.json
- packages/home-assistant-matter-hub/core/src/devices/fan-device.ts
- packages/home-assistant-matter-hub/core/src/devices/light-device.ts
- packages/home-assistant-matter-hub/core/src/devices/utils/if-not-null.ts
- packages/matterbridge-home-assistant-docker/package.json
> fix: commits will not be squashed

- .prettierignore
- eslint.config.js
- package-lock.json
- packages/matterbridge-home-assistant/src/index.ts
> fix(matterbridge): patch NodeAnsiLogger until fix is provided by matterbridge (#262)

- packages/home-assistant-matter-hub/core/src/aspects/on-off-aspect.ts
- packages/home-assistant-matter-hub/core/src/aspects/thermostat-aspect.ts
- packages/home-assistant-matter-hub/core/src/aspects/utils/thermostat-cluster.ts
- packages/home-assistant-matter-hub/core/src/devices/climate-device.ts
- packages/home-assistant-matter-hub/core/src/devices/climate/hvac-mode.ts
- packages/home-assistant-matter-hub/core/src/devices/device-base.ts
- packages/home-assistant-matter-hub/core/src/devices/index.ts
- packages/home-assistant-matter-hub/core/src/devices/matter-device.ts
- packages/home-assistant-matter-hub/core/src/index.ts
- packages/home-assistant-matter-hub/core/src/matter/matter-connector.ts
- packages/matterbridge-home-assistant/src/platform.ts
> feat(climate): enable basic support for climate devices (#47)
